# -*- coding: utf-8 -*-
"""carbonemission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTBMyz_wkVMZd6xxB-yBCKaUC3MQAzof
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df = pd.read_csv("Carbon Emission.csv")
df["Calculated Carbon Emission"] = df["Vehicle Monthly Distance Km"] * 0.2

X, y = df[["Vehicle Monthly Distance Km"]], df["Calculated Carbon Emission"]
model = LinearRegression(fit_intercept=False).fit(X, y)

plt.scatter(X, y, color="blue", label="Data")
plt.plot(X, model.predict(X), color='red', label="Regression")
plt.xlabel("Vehicle Distance (Km)")
plt.ylabel("Carbon Emission (kg CO₂)")
plt.legend()
plt.show()
print(f"Model Accuracy (R² Score): {r2:.4f}")

